### ISSUE TITLE
Add update function to menu

### ISSUE THREAD

**Issue by LjSamardzic** [pobrok/backend#105]
We need to decide in which way this should be made possible. I see two possible ways, but would lean towards the first. Let's discuss. @g1dra @JelenaVucetic @mperovicmrsovic @iRadunovicVega 

1. Allow users to update start and end date of a menu, meaning that behind the scenes we delete or add new menu items based on the given dates. 
2. We allow users to remove days one by one or add one by one, but then have to update the start and/or end date of the menu.

**Comment by d-vucetic** [comment]
We can have a meeting to discuss both, lets say at 14:00 ?

**Comment by LjSamardzic** [comment]
Works for me

**Comment by iRadunovicVega** [comment]
works for me too
