### ISSUE TITLE
CRUD Food

### ISSUE THREAD

**Issue by d-vucetic** [pobrok/backend#4]

**Comment by LjSamardzic** [comment]
@jVucetic I think there is an issue with storing food. Namely, we should attach the user who created the food record, but currently the mapper saves only the user's id. If you add the user instance to the FoodRequest, you can see the data is incomplete.

**Comment by jVucetic** [comment]
@LjSamardzic I saw the issue by adding User to FoodResponse.  User is not saved properly.
 "user": {
        "id": 1,
        "name": null,
        "email": null,
        "role": null,
        "createdAt": null,
        "deleted": false
    }

**Comment by jVucetic** [comment]
@LjSamardzic 
Should we remove user_id from FoodRequest, so we are no longer receiving user through request. Instead we can take the authenticated user on the backend and save it while saving the food?

**Comment by LjSamardzic** [comment]
@jVucetic Definitely, much better security-wise and less code.

**Comment by LjSamardzic** [comment]
@danilokrkeljicvega Jelena is preparing a few changes and she'll mark the issue as closed once it's done.
