### ISSUE TITLE
Handle NoSuchElementException & EmptyResultDataAccessException

### ISSUE THREAD

**Issue by LjSamardzic** [pobrok/backend#78]
The NoSuchElementException is thrown when the path variable is wrong. For instance when we try to update the user with id 4 but that id does not exist. 
The EmptyResultDataAccessException is thrown when attempting to delete a record with an id that does not exist.

**Comment by iRadunovicVega** [comment]
Why dont u use just one exception in both cases, for example EntityNotFoundException?
